# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmergenciesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmergenciesWindow(object):
    def setupUi(self, EmergenciesWindow):
        EmergenciesWindow.setObjectName("EmergenciesWindow")
        EmergenciesWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(EmergenciesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 50, 761, 271))
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 330, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 330, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 21))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(390, 330, 81, 31))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 330, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 370, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 370, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(390, 370, 81, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 370, 161, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 410, 161, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 430, 161, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 430, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        EmergenciesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EmergenciesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        EmergenciesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EmergenciesWindow)
        self.statusbar.setObjectName("statusbar")
        EmergenciesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EmergenciesWindow)
        QtCore.QMetaObject.connectSlotsByName(EmergenciesWindow)

    def retranslateUi(self, EmergenciesWindow):
        _translate = QtCore.QCoreApplication.translate
        EmergenciesWindow.setWindowTitle(_translate("EmergenciesWindow", "MainWindow"))
        self.label.setText(_translate("EmergenciesWindow", "Potential Emergencies"))
        self.checkBox.setText(_translate("EmergenciesWindow", "Covered"))
        self.pushButton.setText(_translate("EmergenciesWindow", "Add Emergency"))
        self.pushButton_2.setText(_translate("EmergenciesWindow", "Edit Emergency"))
        self.checkBox_2.setText(_translate("EmergenciesWindow", "Covered"))
        self.label_2.setText(_translate("EmergenciesWindow", "Enter Your Savings Amount:"))
        self.pushButton_3.setText(_translate("EmergenciesWindow", "Test"))
