# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GroceriesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroceriesEditWindow(object):
    def setupUi(self, GroceriesEditWindow):
        GroceriesEditWindow.setObjectName("GroceriesEditWindow")
        GroceriesEditWindow.resize(800, 523)
        self.centralwidget = QtWidgets.QWidget(GroceriesEditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 361, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(410, 20, 371, 341))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 370, 131, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 370, 191, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 370, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 410, 141, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(162, 370, 71, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(20, 410, 51, 31))
        self.spinBox.setObjectName("spinBox")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 410, 71, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 410, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(610, 370, 71, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 370, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(470, 410, 191, 31))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(410, 410, 51, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(670, 410, 71, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 430, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        GroceriesEditWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GroceriesEditWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        GroceriesEditWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GroceriesEditWindow)
        self.statusbar.setObjectName("statusbar")
        GroceriesEditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GroceriesEditWindow)
        QtCore.QMetaObject.connectSlotsByName(GroceriesEditWindow)

    def retranslateUi(self, GroceriesEditWindow):
        _translate = QtCore.QCoreApplication.translate
        GroceriesEditWindow.setWindowTitle(_translate("GroceriesEditWindow", "MainWindow"))
        self.pushButton.setText(_translate("GroceriesEditWindow", "Add Item"))
        self.pushButton_2.setText(_translate("GroceriesEditWindow", "Edit Item"))
        self.checkBox.setText(_translate("GroceriesEditWindow", "Member"))
        self.pushButton_3.setText(_translate("GroceriesEditWindow", "Add Store"))
        self.checkBox_2.setText(_translate("GroceriesEditWindow", "Member"))
        self.pushButton_4.setText(_translate("GroceriesEditWindow", "Edit Store"))
