# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IncomeEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IncomeEditWindow(object):
    def setupUi(self, IncomeEditWindow):
        IncomeEditWindow.setObjectName("IncomeEditWindow")
        IncomeEditWindow.resize(803, 526)
        self.centralwidget = QtWidgets.QWidget(IncomeEditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.incomeTable = QtWidgets.QTableWidget(self.centralwidget)
        self.incomeTable.setGeometry(QtCore.QRect(20, 50, 401, 241))
        self.incomeTable.setRowCount(0)
        self.incomeTable.setColumnCount(0)
        self.incomeTable.setObjectName("incomeTable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 20, 81, 21))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 221, 20))
        self.label_5.setObjectName("label_5")
        self.taxbrakTable = QtWidgets.QTableWidget(self.centralwidget)
        self.taxbrakTable.setGeometry(QtCore.QRect(440, 50, 291, 411))
        self.taxbrakTable.setRowCount(0)
        self.taxbrakTable.setObjectName("taxbrakTable")
        self.taxbrakTable.setColumnCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 300, 121, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 300, 121, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 300, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(20, 340, 41, 31))
        self.spinBox.setObjectName("spinBox")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 340, 121, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 340, 121, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 340, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.totalLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(20, 380, 151, 31))
        self.totalLabel.setObjectName("totalLabel")
        self.fulltotalLabel = QtWidgets.QLabel(self.centralwidget)
        self.fulltotalLabel.setGeometry(QtCore.QRect(40, 410, 151, 21))
        self.fulltotalLabel.setObjectName("fulltotalLabel")
        IncomeEditWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IncomeEditWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 22))
        self.menubar.setObjectName("menubar")
        IncomeEditWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IncomeEditWindow)
        self.statusbar.setObjectName("statusbar")
        IncomeEditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(IncomeEditWindow)
        QtCore.QMetaObject.connectSlotsByName(IncomeEditWindow)

    def retranslateUi(self, IncomeEditWindow):
        _translate = QtCore.QCoreApplication.translate
        IncomeEditWindow.setWindowTitle(_translate("IncomeEditWindow", "MainWindow"))
        self.label.setText(_translate("IncomeEditWindow", "Tax Bracket"))
        self.label_5.setText(_translate("IncomeEditWindow", "Sources of Income"))
        self.pushButton.setText(_translate("IncomeEditWindow", "Add Income"))
        self.pushButton_2.setText(_translate("IncomeEditWindow", "Edit Income"))
        self.totalLabel.setText(_translate("IncomeEditWindow", "Current Income Total:"))
        self.fulltotalLabel.setText(_translate("IncomeEditWindow", "To Be Determined"))
